version: "3"
services:
  dbserver:
    container_name: mysql5.7_demo_sample
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: demo_sample_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      # MySQLの設定ファイル
      - ./docker-compose/mysql/config:/etc/mysql/conf.d
      # DBの永続化
      - mysql_db:/var/lib/mysql
  app:
    container_name: spring_app
    build:
      context: ./
      args:
        - JAR_FILE=build/libs/springBootWithDocker.jar
    depends_on:
      # dbserverが起動してから、appを起動
      - dbserver
    ports:
      - "8080:8080"
    environment:
      # mysqlの接続設定 host:portはコンテナ名指定
      spring.datasource.driverClassName: "com.mysql.cj.jdbc.Driver"
      spring.datasource.url: "jdbc:mysql://dbserver/mysql5.7_demo_sample"
      spring.datasource.username: "user"
      spring.datasource.password: "password"
# DBの永続化先
volumes:
  mysql_db:
    driver: local